name: CI/CD

on:
  push:
    branches:
      - main

env:
  VERSION: 0.1.0-dev
  NODE_VERSION: 20.11.1

jobs:
  deploy-on-hosting-server:
    name: Deploy on hosting server
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Prepare
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create env
        uses: 'DamianReeves/write-file-action@master'
        with:
          path: './.env'
          write-mode: overwrite
          contents: |
            VITE_API_URL="https://meteor-bt.com"
      - name: Build
        run: |
          node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'
          yarn install
          yarn build

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_SECRET_KEY }}
          port: 22
          source: './dist/*'
          target: /var/www/html
          rm: true
